### ISSUE TITLE
macos compile

### ISSUE THREAD

**Issue by hy05190134** [cloudflare/lua-aho-corasick#7]
it is not supported by macos, so I hope you it can be compatible  for macos

**Comment by yangshuxin** [comment]
Sorry about that, the piece of code is implemented and tested on Linux only. I didn't get chance to compile and test it on MacOS  (I don't have MacOS at work, and my workhorse at home is still Linux -- I'm a diehard Linux user:-)). 

The compile problem should be pretty easy to fix. I do have MacOS at home. I will fix the problem ASAP.

**Comment by yangshuxin** [comment]
Fixed as of commit 8fbe0bfa72642ac327b7cce9c2b5add9f3758893
